#!/usr/bin/env sh

GENFILE="segments.zig"

FILES=./src/zgzero/__gen/images/seg*

echo "pub fn segment_list(list: *zgame.Canvas.List, renderer: zgame.sdl.Renderer) !void {" >$GENFILE

for FILE in $FILES; do
    VAR_NAME=$(echo "${FILE##*/}" | cut -f 1 -d '.')
    FILE_PATH="./sounds/${FILE##*/}"
    echo "    try list.append(try zgame.Canvas.loadPng(renderer, images.$VAR_NAME));" >>$GENFILE
done

echo "}" >>$GENFILE
